# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ctw_123
    volumes:
      - microservices_devdojo:/var/lib/postgres

volumes:
  microservices_devdojo:
