server:
  port: 8080

spring:
  application:
    name: microservices
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/devdojo
    username: root
    password: ctw_123


